/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.AchievementsDependsOn;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Achievements implements Serializable {

    private static final long serialVersionUID = -979373674;

    private Long                  id;
    private Long                  domainId;
    private String                name;
    private String                batchName;
    private String                title;
    private Timestamp             startTime;
    private Timestamp             endTime;
    private Long                  pointsLvl1;
    private Long                  pointsLvl2;
    private Long                  pointsLvl3;
    private Long                  pointsLvl4;
    private String                descriptionLvl1;
    private String                descriptionLvl2;
    private String                descriptionLvl3;
    private String                descriptionLvl4;
    private AchievementsDependsOn dependsOn;
    private Boolean               isVisible;

    public Achievements() {}

    public Achievements(Achievements value) {
        this.id = value.id;
        this.domainId = value.domainId;
        this.name = value.name;
        this.batchName = value.batchName;
        this.title = value.title;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.pointsLvl1 = value.pointsLvl1;
        this.pointsLvl2 = value.pointsLvl2;
        this.pointsLvl3 = value.pointsLvl3;
        this.pointsLvl4 = value.pointsLvl4;
        this.descriptionLvl1 = value.descriptionLvl1;
        this.descriptionLvl2 = value.descriptionLvl2;
        this.descriptionLvl3 = value.descriptionLvl3;
        this.descriptionLvl4 = value.descriptionLvl4;
        this.dependsOn = value.dependsOn;
        this.isVisible = value.isVisible;
    }

    public Achievements(
        Long                  id,
        Long                  domainId,
        String                name,
        String                batchName,
        String                title,
        Timestamp             startTime,
        Timestamp             endTime,
        Long                  pointsLvl1,
        Long                  pointsLvl2,
        Long                  pointsLvl3,
        Long                  pointsLvl4,
        String                descriptionLvl1,
        String                descriptionLvl2,
        String                descriptionLvl3,
        String                descriptionLvl4,
        AchievementsDependsOn dependsOn,
        Boolean               isVisible
    ) {
        this.id = id;
        this.domainId = domainId;
        this.name = name;
        this.batchName = batchName;
        this.title = title;
        this.startTime = startTime;
        this.endTime = endTime;
        this.pointsLvl1 = pointsLvl1;
        this.pointsLvl2 = pointsLvl2;
        this.pointsLvl3 = pointsLvl3;
        this.pointsLvl4 = pointsLvl4;
        this.descriptionLvl1 = descriptionLvl1;
        this.descriptionLvl2 = descriptionLvl2;
        this.descriptionLvl3 = descriptionLvl3;
        this.descriptionLvl4 = descriptionLvl4;
        this.dependsOn = dependsOn;
        this.isVisible = isVisible;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDomainId() {
        return this.domainId;
    }

    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    @Size(max = 65535)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 65535)
    public String getBatchName() {
        return this.batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    @Size(max = 65535)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Timestamp getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    public Timestamp getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    public Long getPointsLvl1() {
        return this.pointsLvl1;
    }

    public void setPointsLvl1(Long pointsLvl1) {
        this.pointsLvl1 = pointsLvl1;
    }

    public Long getPointsLvl2() {
        return this.pointsLvl2;
    }

    public void setPointsLvl2(Long pointsLvl2) {
        this.pointsLvl2 = pointsLvl2;
    }

    public Long getPointsLvl3() {
        return this.pointsLvl3;
    }

    public void setPointsLvl3(Long pointsLvl3) {
        this.pointsLvl3 = pointsLvl3;
    }

    public Long getPointsLvl4() {
        return this.pointsLvl4;
    }

    public void setPointsLvl4(Long pointsLvl4) {
        this.pointsLvl4 = pointsLvl4;
    }

    @Size(max = 65535)
    public String getDescriptionLvl1() {
        return this.descriptionLvl1;
    }

    public void setDescriptionLvl1(String descriptionLvl1) {
        this.descriptionLvl1 = descriptionLvl1;
    }

    @Size(max = 65535)
    public String getDescriptionLvl2() {
        return this.descriptionLvl2;
    }

    public void setDescriptionLvl2(String descriptionLvl2) {
        this.descriptionLvl2 = descriptionLvl2;
    }

    @Size(max = 65535)
    public String getDescriptionLvl3() {
        return this.descriptionLvl3;
    }

    public void setDescriptionLvl3(String descriptionLvl3) {
        this.descriptionLvl3 = descriptionLvl3;
    }

    @Size(max = 65535)
    public String getDescriptionLvl4() {
        return this.descriptionLvl4;
    }

    public void setDescriptionLvl4(String descriptionLvl4) {
        this.descriptionLvl4 = descriptionLvl4;
    }

    @NotNull
    public AchievementsDependsOn getDependsOn() {
        return this.dependsOn;
    }

    public void setDependsOn(AchievementsDependsOn dependsOn) {
        this.dependsOn = dependsOn;
    }

    public Boolean getIsVisible() {
        return this.isVisible;
    }

    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Achievements (");

        sb.append(id);
        sb.append(", ").append(domainId);
        sb.append(", ").append(name);
        sb.append(", ").append(batchName);
        sb.append(", ").append(title);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(pointsLvl1);
        sb.append(", ").append(pointsLvl2);
        sb.append(", ").append(pointsLvl3);
        sb.append(", ").append(pointsLvl4);
        sb.append(", ").append(descriptionLvl1);
        sb.append(", ").append(descriptionLvl2);
        sb.append(", ").append(descriptionLvl3);
        sb.append(", ").append(descriptionLvl4);
        sb.append(", ").append(dependsOn);
        sb.append(", ").append(isVisible);

        sb.append(")");
        return sb.toString();
    }
}
