/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.CheckedDataElementType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedDataElement implements Serializable {

    private static final long serialVersionUID = -659727520;

    private Long                   id;
    private Long                   userId;
    private Long                   dataElementId;
    private CheckedDataElementType type;
    private Timestamp              createdTime;

    public CheckedDataElement() {}

    public CheckedDataElement(CheckedDataElement value) {
        this.id = value.id;
        this.userId = value.userId;
        this.dataElementId = value.dataElementId;
        this.type = value.type;
        this.createdTime = value.createdTime;
    }

    public CheckedDataElement(
        Long                   id,
        Long                   userId,
        Long                   dataElementId,
        CheckedDataElementType type,
        Timestamp              createdTime
    ) {
        this.id = id;
        this.userId = userId;
        this.dataElementId = dataElementId;
        this.type = type;
        this.createdTime = createdTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @NotNull
    public Long getDataElementId() {
        return this.dataElementId;
    }

    public void setDataElementId(Long dataElementId) {
        this.dataElementId = dataElementId;
    }

    @NotNull
    public CheckedDataElementType getType() {
        return this.type;
    }

    public void setType(CheckedDataElementType type) {
        this.type = type;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckedDataElement (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(dataElementId);
        sb.append(", ").append(type);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
