/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.CheckedDataTupleType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedDataTuple implements Serializable {

    private static final long serialVersionUID = 1744138536;

    private Long                 id;
    private Long                 userId;
    private Long                 dataTupleId;
    private CheckedDataTupleType type;
    private Timestamp            createdTime;

    public CheckedDataTuple() {}

    public CheckedDataTuple(CheckedDataTuple value) {
        this.id = value.id;
        this.userId = value.userId;
        this.dataTupleId = value.dataTupleId;
        this.type = value.type;
        this.createdTime = value.createdTime;
    }

    public CheckedDataTuple(
        Long                 id,
        Long                 userId,
        Long                 dataTupleId,
        CheckedDataTupleType type,
        Timestamp            createdTime
    ) {
        this.id = id;
        this.userId = userId;
        this.dataTupleId = dataTupleId;
        this.type = type;
        this.createdTime = createdTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @NotNull
    public Long getDataTupleId() {
        return this.dataTupleId;
    }

    public void setDataTupleId(Long dataTupleId) {
        this.dataTupleId = dataTupleId;
    }

    @NotNull
    public CheckedDataTupleType getType() {
        return this.type;
    }

    public void setType(CheckedDataTupleType type) {
        this.type = type;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckedDataTuple (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(dataTupleId);
        sb.append(", ").append(type);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
