/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElement implements Serializable {

    private static final long serialVersionUID = 762318726;

    private Long      id;
    private Long      sourceId;
    private Long      userId;
    private Long      userGroupId;
    private Timestamp createdTime;
    private Boolean   finished;
    private Boolean   isPrivate;
    private Long      skipped;

    public DataElement() {}

    public DataElement(DataElement value) {
        this.id = value.id;
        this.sourceId = value.sourceId;
        this.userId = value.userId;
        this.userGroupId = value.userGroupId;
        this.createdTime = value.createdTime;
        this.finished = value.finished;
        this.isPrivate = value.isPrivate;
        this.skipped = value.skipped;
    }

    public DataElement(
        Long      id,
        Long      sourceId,
        Long      userId,
        Long      userGroupId,
        Timestamp createdTime,
        Boolean   finished,
        Boolean   isPrivate,
        Long      skipped
    ) {
        this.id = id;
        this.sourceId = sourceId;
        this.userId = userId;
        this.userGroupId = userGroupId;
        this.createdTime = createdTime;
        this.finished = finished;
        this.isPrivate = isPrivate;
        this.skipped = skipped;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @NotNull
    public Long getUserGroupId() {
        return this.userGroupId;
    }

    public void setUserGroupId(Long userGroupId) {
        this.userGroupId = userGroupId;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Boolean getFinished() {
        return this.finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    public Boolean getIsPrivate() {
        return this.isPrivate;
    }

    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    public Long getSkipped() {
        return this.skipped;
    }

    public void setSkipped(Long skipped) {
        this.skipped = skipped;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataElement (");

        sb.append(id);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(userId);
        sb.append(", ").append(userGroupId);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(finished);
        sb.append(", ").append(isPrivate);
        sb.append(", ").append(skipped);

        sb.append(")");
        return sb.toString();
    }
}
