/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.DataTupleType;

import java.io.Serializable;

import javax.validation.constraints.NotNull;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataTuple implements Serializable {

    private static final long serialVersionUID = 2040726939;

    private Long          id;
    private Long          dataElementId_1;
    private Long          dataElementId_2;
    private DataTupleType type;
    private Boolean       finished;
    private Long          correct;
    private Long          wrong;
    private Long          skipped;

    public DataTuple() {}

    public DataTuple(DataTuple value) {
        this.id = value.id;
        this.dataElementId_1 = value.dataElementId_1;
        this.dataElementId_2 = value.dataElementId_2;
        this.type = value.type;
        this.finished = value.finished;
        this.correct = value.correct;
        this.wrong = value.wrong;
        this.skipped = value.skipped;
    }

    public DataTuple(
        Long          id,
        Long          dataElementId_1,
        Long          dataElementId_2,
        DataTupleType type,
        Boolean       finished,
        Long          correct,
        Long          wrong,
        Long          skipped
    ) {
        this.id = id;
        this.dataElementId_1 = dataElementId_1;
        this.dataElementId_2 = dataElementId_2;
        this.type = type;
        this.finished = finished;
        this.correct = correct;
        this.wrong = wrong;
        this.skipped = skipped;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getDataElementId_1() {
        return this.dataElementId_1;
    }

    public void setDataElementId_1(Long dataElementId_1) {
        this.dataElementId_1 = dataElementId_1;
    }

    @NotNull
    public Long getDataElementId_2() {
        return this.dataElementId_2;
    }

    public void setDataElementId_2(Long dataElementId_2) {
        this.dataElementId_2 = dataElementId_2;
    }

    public DataTupleType getType() {
        return this.type;
    }

    public void setType(DataTupleType type) {
        this.type = type;
    }

    public Boolean getFinished() {
        return this.finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    public Long getCorrect() {
        return this.correct;
    }

    public void setCorrect(Long correct) {
        this.correct = correct;
    }

    public Long getWrong() {
        return this.wrong;
    }

    public void setWrong(Long wrong) {
        this.wrong = wrong;
    }

    public Long getSkipped() {
        return this.skipped;
    }

    public void setSkipped(Long skipped) {
        this.skipped = skipped;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataTuple (");

        sb.append(id);
        sb.append(", ").append(dataElementId_1);
        sb.append(", ").append(dataElementId_2);
        sb.append(", ").append(type);
        sb.append(", ").append(finished);
        sb.append(", ").append(correct);
        sb.append(", ").append(wrong);
        sb.append(", ").append(skipped);

        sb.append(")");
        return sb.toString();
    }
}
