/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Excerpt implements Serializable {

    private static final long serialVersionUID = -1314399418;

    private Long    id;
    private Long    originalTextId;
    private String  excerpt;
    private Integer isSkipped;
    private Boolean isPrivate;
    private Boolean isSentenceError;

    public Excerpt() {}

    public Excerpt(Excerpt value) {
        this.id = value.id;
        this.originalTextId = value.originalTextId;
        this.excerpt = value.excerpt;
        this.isSkipped = value.isSkipped;
        this.isPrivate = value.isPrivate;
        this.isSentenceError = value.isSentenceError;
    }

    public Excerpt(
        Long    id,
        Long    originalTextId,
        String  excerpt,
        Integer isSkipped,
        Boolean isPrivate,
        Boolean isSentenceError
    ) {
        this.id = id;
        this.originalTextId = originalTextId;
        this.excerpt = excerpt;
        this.isSkipped = isSkipped;
        this.isPrivate = isPrivate;
        this.isSentenceError = isSentenceError;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getOriginalTextId() {
        return this.originalTextId;
    }

    public void setOriginalTextId(Long originalTextId) {
        this.originalTextId = originalTextId;
    }

    @NotNull
    @Size(max = 65535)
    public String getExcerpt() {
        return this.excerpt;
    }

    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt;
    }

    public Integer getIsSkipped() {
        return this.isSkipped;
    }

    public void setIsSkipped(Integer isSkipped) {
        this.isSkipped = isSkipped;
    }

    public Boolean getIsPrivate() {
        return this.isPrivate;
    }

    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    public Boolean getIsSentenceError() {
        return this.isSentenceError;
    }

    public void setIsSentenceError(Boolean isSentenceError) {
        this.isSentenceError = isSentenceError;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Excerpt (");

        sb.append(id);
        sb.append(", ").append(originalTextId);
        sb.append(", ").append(excerpt);
        sb.append(", ").append(isSkipped);
        sb.append(", ").append(isPrivate);
        sb.append(", ").append(isSentenceError);

        sb.append(")");
        return sb.toString();
    }
}
