/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Image implements Serializable {

    private static final long serialVersionUID = 411106228;

    private Long   id;
    private Long   dataElementId;
    private String path;
    private String licence;

    public Image() {}

    public Image(Image value) {
        this.id = value.id;
        this.dataElementId = value.dataElementId;
        this.path = value.path;
        this.licence = value.licence;
    }

    public Image(
        Long   id,
        Long   dataElementId,
        String path,
        String licence
    ) {
        this.id = id;
        this.dataElementId = dataElementId;
        this.path = path;
        this.licence = licence;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Long getDataElementId() {
        return this.dataElementId;
    }

    public void setDataElementId(Long dataElementId) {
        this.dataElementId = dataElementId;
    }

    @NotNull
    @Size(max = 65535)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Size(max = 65535)
    public String getLicence() {
        return this.licence;
    }

    public void setLicence(String licence) {
        this.licence = licence;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Image (");

        sb.append(id);
        sb.append(", ").append(dataElementId);
        sb.append(", ").append(path);
        sb.append(", ").append(licence);

        sb.append(")");
        return sb.toString();
    }
}
