/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import java.io.Serializable;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAchievements implements Serializable {

    private static final long serialVersionUID = -552837808;

    private Long    id;
    private Long    userId;
    private Long    achievementsId;
    private Long    points;
    private Boolean isNew;

    public UserAchievements() {}

    public UserAchievements(UserAchievements value) {
        this.id = value.id;
        this.userId = value.userId;
        this.achievementsId = value.achievementsId;
        this.points = value.points;
        this.isNew = value.isNew;
    }

    public UserAchievements(
        Long    id,
        Long    userId,
        Long    achievementsId,
        Long    points,
        Boolean isNew
    ) {
        this.id = id;
        this.userId = userId;
        this.achievementsId = achievementsId;
        this.points = points;
        this.isNew = isNew;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getAchievementsId() {
        return this.achievementsId;
    }

    public void setAchievementsId(Long achievementsId) {
        this.achievementsId = achievementsId;
    }

    public Long getPoints() {
        return this.points;
    }

    public void setPoints(Long points) {
        this.points = points;
    }

    public Boolean getIsNew() {
        return this.isNew;
    }

    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAchievements (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(achievementsId);
        sb.append(", ").append(points);
        sb.append(", ").append(isNew);

        sb.append(")");
        return sb.toString();
    }
}
