/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.UserAge;
import ch.fhnw.speech_collection_app.jooq.enums.UserLicence;
import ch.fhnw.speech_collection_app.jooq.enums.UserSex;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1188364624;

    private Long        id;
    private String      firstName;
    private String      lastName;
    private String      email;
    private String      username;
    private String      password;
    private UserSex     sex;
    private UserLicence licence;
    private UserAge     age;
    private Boolean     enabled;
    private Long        dialectId;
    private Boolean     notCh;
    private String      zipCode;
    private Timestamp   lastOnline;
    private Boolean     gamificationOn;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.username = value.username;
        this.password = value.password;
        this.sex = value.sex;
        this.licence = value.licence;
        this.age = value.age;
        this.enabled = value.enabled;
        this.dialectId = value.dialectId;
        this.notCh = value.notCh;
        this.zipCode = value.zipCode;
        this.lastOnline = value.lastOnline;
        this.gamificationOn = value.gamificationOn;
    }

    public User(
        Long        id,
        String      firstName,
        String      lastName,
        String      email,
        String      username,
        String      password,
        UserSex     sex,
        UserLicence licence,
        UserAge     age,
        Boolean     enabled,
        Long        dialectId,
        Boolean     notCh,
        String      zipCode,
        Timestamp   lastOnline,
        Boolean     gamificationOn
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.username = username;
        this.password = password;
        this.sex = sex;
        this.licence = licence;
        this.age = age;
        this.enabled = enabled;
        this.dialectId = dialectId;
        this.notCh = notCh;
        this.zipCode = zipCode;
        this.lastOnline = lastOnline;
        this.gamificationOn = gamificationOn;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Size(max = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @NotNull
    @Size(max = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @NotNull
    @Size(max = 100)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserSex getSex() {
        return this.sex;
    }

    public void setSex(UserSex sex) {
        this.sex = sex;
    }

    public UserLicence getLicence() {
        return this.licence;
    }

    public void setLicence(UserLicence licence) {
        this.licence = licence;
    }

    public UserAge getAge() {
        return this.age;
    }

    public void setAge(UserAge age) {
        this.age = age;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @NotNull
    public Long getDialectId() {
        return this.dialectId;
    }

    public void setDialectId(Long dialectId) {
        this.dialectId = dialectId;
    }

    public Boolean getNotCh() {
        return this.notCh;
    }

    public void setNotCh(Boolean notCh) {
        this.notCh = notCh;
    }

    @Size(max = 45)
    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public Timestamp getLastOnline() {
        return this.lastOnline;
    }

    public void setLastOnline(Timestamp lastOnline) {
        this.lastOnline = lastOnline;
    }

    public Boolean getGamificationOn() {
        return this.gamificationOn;
    }

    public void setGamificationOn(Boolean gamificationOn) {
        this.gamificationOn = gamificationOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(sex);
        sb.append(", ").append(licence);
        sb.append(", ").append(age);
        sb.append(", ").append(enabled);
        sb.append(", ").append(dialectId);
        sb.append(", ").append(notCh);
        sb.append(", ").append(zipCode);
        sb.append(", ").append(lastOnline);
        sb.append(", ").append(gamificationOn);

        sb.append(")");
        return sb.toString();
    }
}
