/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroup implements Serializable {

    private static final long serialVersionUID = -1013519199;

    private Long   id;
    private String name;
    private String description;
    private String metaInformation;

    public UserGroup() {}

    public UserGroup(UserGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.metaInformation = value.metaInformation;
    }

    public UserGroup(
        Long   id,
        String name,
        String description,
        String metaInformation
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.metaInformation = metaInformation;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 16777215)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMetaInformation() {
        return this.metaInformation;
    }

    public void setMetaInformation(String metaInformation) {
        this.metaInformation = metaInformation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(metaInformation);

        sb.append(")");
        return sb.toString();
    }
}
