/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.pojos;


import ch.fhnw.speech_collection_app.jooq.enums.VerificationTokenTokenType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationToken implements Serializable {

    private static final long serialVersionUID = -1704737724;

    private Long                       id;
    private String                     token;
    private VerificationTokenTokenType tokenType;
    private Timestamp                  createdTime;
    private Long                       userId;

    public VerificationToken() {}

    public VerificationToken(VerificationToken value) {
        this.id = value.id;
        this.token = value.token;
        this.tokenType = value.tokenType;
        this.createdTime = value.createdTime;
        this.userId = value.userId;
    }

    public VerificationToken(
        Long                       id,
        String                     token,
        VerificationTokenTokenType tokenType,
        Timestamp                  createdTime,
        Long                       userId
    ) {
        this.id = id;
        this.token = token;
        this.tokenType = tokenType;
        this.createdTime = createdTime;
        this.userId = userId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 65535)
    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @NotNull
    public VerificationTokenTokenType getTokenType() {
        return this.tokenType;
    }

    public void setTokenType(VerificationTokenTokenType tokenType) {
        this.tokenType = tokenType;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VerificationToken (");

        sb.append(id);
        sb.append(", ").append(token);
        sb.append(", ").append(tokenType);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
