ALTER TABLE user
    MODIFY COLUMN age ENUM ('NONE','U20','U30','U40','U50','U60','U70','U80','O80') DEFAULT 'NONE',
    MODIFY COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE,
    MODIFY COLUMN not_CH BOOLEAN NOT NULL DEFAULT FALSE;
