/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.labeling_tool.jooq.tables.records;


import ch.fhnw.labeling_tool.jooq.enums.VerificationTokenTokenType;
import ch.fhnw.labeling_tool.jooq.tables.VerificationToken;

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationTokenRecord extends UpdatableRecordImpl<VerificationTokenRecord> implements Record5<Long, String, VerificationTokenTokenType, Timestamp, Long> {

    private static final long serialVersionUID = 968419008;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setToken(String value) {
        set(1, value);
    }

    @NotNull
    @Size(max = 65535)
    public String getToken() {
        return (String) get(1);
    }

    public void setTokenType(VerificationTokenTokenType value) {
        set(2, value);
    }

    @NotNull
    public VerificationTokenTokenType getTokenType() {
        return (VerificationTokenTokenType) get(2);
    }

    public void setCreatedTime(Timestamp value) {
        set(3, value);
    }

    public Timestamp getCreatedTime() {
        return (Timestamp) get(3);
    }

    public void setUserId(Long value) {
        set(4, value);
    }

    @NotNull
    public Long getUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, VerificationTokenTokenType, Timestamp, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, VerificationTokenTokenType, Timestamp, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VerificationToken.VERIFICATION_TOKEN.ID;
    }

    @Override
    public Field<String> field2() {
        return VerificationToken.VERIFICATION_TOKEN.TOKEN;
    }

    @Override
    public Field<VerificationTokenTokenType> field3() {
        return VerificationToken.VERIFICATION_TOKEN.TOKEN_TYPE;
    }

    @Override
    public Field<Timestamp> field4() {
        return VerificationToken.VERIFICATION_TOKEN.CREATED_TIME;
    }

    @Override
    public Field<Long> field5() {
        return VerificationToken.VERIFICATION_TOKEN.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getToken();
    }

    @Override
    public VerificationTokenTokenType component3() {
        return getTokenType();
    }

    @Override
    public Timestamp component4() {
        return getCreatedTime();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getToken();
    }

    @Override
    public VerificationTokenTokenType value3() {
        return getTokenType();
    }

    @Override
    public Timestamp value4() {
        return getCreatedTime();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public VerificationTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value2(String value) {
        setToken(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value3(VerificationTokenTokenType value) {
        setTokenType(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value4(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public VerificationTokenRecord values(Long value1, String value2, VerificationTokenTokenType value3, Timestamp value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public VerificationTokenRecord() {
        super(VerificationToken.VERIFICATION_TOKEN);
    }

    public VerificationTokenRecord(Long id, String token, VerificationTokenTokenType tokenType, Timestamp createdTime, Long userId) {
        super(VerificationToken.VERIFICATION_TOKEN);

        set(0, id);
        set(1, token);
        set(2, tokenType);
        set(3, createdTime);
        set(4, userId);
    }
}
