/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.records;


import ch.fhnw.speech_collection_app.jooq.enums.AchievementsDependsOn;
import ch.fhnw.speech_collection_app.jooq.tables.Achievements;

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AchievementsRecord extends UpdatableRecordImpl<AchievementsRecord> implements Record16<Long, Long, String, String, String, Timestamp, Timestamp, Long, Long, Long, Long, String, String, String, String, AchievementsDependsOn> {

    private static final long serialVersionUID = 985681996;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setDomainId(Long value) {
        set(1, value);
    }

    public Long getDomainId() {
        return (Long) get(1);
    }

    public void setName(String value) {
        set(2, value);
    }

    @Size(max = 65535)
    public String getName() {
        return (String) get(2);
    }

    public void setBatchName(String value) {
        set(3, value);
    }

    @Size(max = 65535)
    public String getBatchName() {
        return (String) get(3);
    }

    public void setTitle(String value) {
        set(4, value);
    }

    @Size(max = 65535)
    public String getTitle() {
        return (String) get(4);
    }

    public void setStartTime(Timestamp value) {
        set(5, value);
    }

    public Timestamp getStartTime() {
        return (Timestamp) get(5);
    }

    public void setEndTime(Timestamp value) {
        set(6, value);
    }

    public Timestamp getEndTime() {
        return (Timestamp) get(6);
    }

    public void setPointsLvl1(Long value) {
        set(7, value);
    }

    public Long getPointsLvl1() {
        return (Long) get(7);
    }

    public void setPointsLvl2(Long value) {
        set(8, value);
    }

    public Long getPointsLvl2() {
        return (Long) get(8);
    }

    public void setPointsLvl3(Long value) {
        set(9, value);
    }

    public Long getPointsLvl3() {
        return (Long) get(9);
    }

    public void setPointsLvl4(Long value) {
        set(10, value);
    }

    public Long getPointsLvl4() {
        return (Long) get(10);
    }

    public void setDescriptionLvl1(String value) {
        set(11, value);
    }

    @Size(max = 65535)
    public String getDescriptionLvl1() {
        return (String) get(11);
    }

    public void setDescriptionLvl2(String value) {
        set(12, value);
    }

    @Size(max = 65535)
    public String getDescriptionLvl2() {
        return (String) get(12);
    }

    public void setDescriptionLvl3(String value) {
        set(13, value);
    }

    @Size(max = 65535)
    public String getDescriptionLvl3() {
        return (String) get(13);
    }

    public void setDescriptionLvl4(String value) {
        set(14, value);
    }

    @Size(max = 65535)
    public String getDescriptionLvl4() {
        return (String) get(14);
    }

    public void setDependsOn(AchievementsDependsOn value) {
        set(15, value);
    }

    @NotNull
    public AchievementsDependsOn getDependsOn() {
        return (AchievementsDependsOn) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, String, String, String, Timestamp, Timestamp, Long, Long, Long, Long, String, String, String, String, AchievementsDependsOn> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, Long, String, String, String, Timestamp, Timestamp, Long, Long, Long, Long, String, String, String, String, AchievementsDependsOn> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Achievements.ACHIEVEMENTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Achievements.ACHIEVEMENTS.DOMAIN_ID;
    }

    @Override
    public Field<String> field3() {
        return Achievements.ACHIEVEMENTS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Achievements.ACHIEVEMENTS.BATCH_NAME;
    }

    @Override
    public Field<String> field5() {
        return Achievements.ACHIEVEMENTS.TITLE;
    }

    @Override
    public Field<Timestamp> field6() {
        return Achievements.ACHIEVEMENTS.START_TIME;
    }

    @Override
    public Field<Timestamp> field7() {
        return Achievements.ACHIEVEMENTS.END_TIME;
    }

    @Override
    public Field<Long> field8() {
        return Achievements.ACHIEVEMENTS.POINTS_LVL1;
    }

    @Override
    public Field<Long> field9() {
        return Achievements.ACHIEVEMENTS.POINTS_LVL2;
    }

    @Override
    public Field<Long> field10() {
        return Achievements.ACHIEVEMENTS.POINTS_LVL3;
    }

    @Override
    public Field<Long> field11() {
        return Achievements.ACHIEVEMENTS.POINTS_LVL4;
    }

    @Override
    public Field<String> field12() {
        return Achievements.ACHIEVEMENTS.DESCRIPTION_LVL1;
    }

    @Override
    public Field<String> field13() {
        return Achievements.ACHIEVEMENTS.DESCRIPTION_LVL2;
    }

    @Override
    public Field<String> field14() {
        return Achievements.ACHIEVEMENTS.DESCRIPTION_LVL3;
    }

    @Override
    public Field<String> field15() {
        return Achievements.ACHIEVEMENTS.DESCRIPTION_LVL4;
    }

    @Override
    public Field<AchievementsDependsOn> field16() {
        return Achievements.ACHIEVEMENTS.DEPENDS_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDomainId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getBatchName();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public Timestamp component6() {
        return getStartTime();
    }

    @Override
    public Timestamp component7() {
        return getEndTime();
    }

    @Override
    public Long component8() {
        return getPointsLvl1();
    }

    @Override
    public Long component9() {
        return getPointsLvl2();
    }

    @Override
    public Long component10() {
        return getPointsLvl3();
    }

    @Override
    public Long component11() {
        return getPointsLvl4();
    }

    @Override
    public String component12() {
        return getDescriptionLvl1();
    }

    @Override
    public String component13() {
        return getDescriptionLvl2();
    }

    @Override
    public String component14() {
        return getDescriptionLvl3();
    }

    @Override
    public String component15() {
        return getDescriptionLvl4();
    }

    @Override
    public AchievementsDependsOn component16() {
        return getDependsOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDomainId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getBatchName();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public Timestamp value6() {
        return getStartTime();
    }

    @Override
    public Timestamp value7() {
        return getEndTime();
    }

    @Override
    public Long value8() {
        return getPointsLvl1();
    }

    @Override
    public Long value9() {
        return getPointsLvl2();
    }

    @Override
    public Long value10() {
        return getPointsLvl3();
    }

    @Override
    public Long value11() {
        return getPointsLvl4();
    }

    @Override
    public String value12() {
        return getDescriptionLvl1();
    }

    @Override
    public String value13() {
        return getDescriptionLvl2();
    }

    @Override
    public String value14() {
        return getDescriptionLvl3();
    }

    @Override
    public String value15() {
        return getDescriptionLvl4();
    }

    @Override
    public AchievementsDependsOn value16() {
        return getDependsOn();
    }

    @Override
    public AchievementsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AchievementsRecord value2(Long value) {
        setDomainId(value);
        return this;
    }

    @Override
    public AchievementsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AchievementsRecord value4(String value) {
        setBatchName(value);
        return this;
    }

    @Override
    public AchievementsRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public AchievementsRecord value6(Timestamp value) {
        setStartTime(value);
        return this;
    }

    @Override
    public AchievementsRecord value7(Timestamp value) {
        setEndTime(value);
        return this;
    }

    @Override
    public AchievementsRecord value8(Long value) {
        setPointsLvl1(value);
        return this;
    }

    @Override
    public AchievementsRecord value9(Long value) {
        setPointsLvl2(value);
        return this;
    }

    @Override
    public AchievementsRecord value10(Long value) {
        setPointsLvl3(value);
        return this;
    }

    @Override
    public AchievementsRecord value11(Long value) {
        setPointsLvl4(value);
        return this;
    }

    @Override
    public AchievementsRecord value12(String value) {
        setDescriptionLvl1(value);
        return this;
    }

    @Override
    public AchievementsRecord value13(String value) {
        setDescriptionLvl2(value);
        return this;
    }

    @Override
    public AchievementsRecord value14(String value) {
        setDescriptionLvl3(value);
        return this;
    }

    @Override
    public AchievementsRecord value15(String value) {
        setDescriptionLvl4(value);
        return this;
    }

    @Override
    public AchievementsRecord value16(AchievementsDependsOn value) {
        setDependsOn(value);
        return this;
    }

    @Override
    public AchievementsRecord values(Long value1, Long value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Long value8, Long value9, Long value10, Long value11, String value12, String value13, String value14, String value15, AchievementsDependsOn value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public AchievementsRecord() {
        super(Achievements.ACHIEVEMENTS);
    }

    public AchievementsRecord(Long id, Long domainId, String name, String batchName, String title, Timestamp startTime, Timestamp endTime, Long pointsLvl1, Long pointsLvl2, Long pointsLvl3, Long pointsLvl4, String descriptionLvl1, String descriptionLvl2, String descriptionLvl3, String descriptionLvl4, AchievementsDependsOn dependsOn) {
        super(Achievements.ACHIEVEMENTS);

        set(0, id);
        set(1, domainId);
        set(2, name);
        set(3, batchName);
        set(4, title);
        set(5, startTime);
        set(6, endTime);
        set(7, pointsLvl1);
        set(8, pointsLvl2);
        set(9, pointsLvl3);
        set(10, pointsLvl4);
        set(11, descriptionLvl1);
        set(12, descriptionLvl2);
        set(13, descriptionLvl3);
        set(14, descriptionLvl4);
        set(15, dependsOn);
    }
}
