/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.records;


import ch.fhnw.speech_collection_app.jooq.enums.CheckedDataElementType;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataElement;

import java.sql.Timestamp;

import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedDataElementRecord extends UpdatableRecordImpl<CheckedDataElementRecord> implements Record5<Long, Long, Long, CheckedDataElementType, Timestamp> {

    private static final long serialVersionUID = 1309953868;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setUserId(Long value) {
        set(1, value);
    }

    @NotNull
    public Long getUserId() {
        return (Long) get(1);
    }

    public void setDataElementId(Long value) {
        set(2, value);
    }

    @NotNull
    public Long getDataElementId() {
        return (Long) get(2);
    }

    public void setType(CheckedDataElementType value) {
        set(3, value);
    }

    @NotNull
    public CheckedDataElementType getType() {
        return (CheckedDataElementType) get(3);
    }

    public void setCreatedTime(Timestamp value) {
        set(4, value);
    }

    public Timestamp getCreatedTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, CheckedDataElementType, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, CheckedDataElementType, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CheckedDataElement.CHECKED_DATA_ELEMENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return CheckedDataElement.CHECKED_DATA_ELEMENT.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return CheckedDataElement.CHECKED_DATA_ELEMENT.DATA_ELEMENT_ID;
    }

    @Override
    public Field<CheckedDataElementType> field4() {
        return CheckedDataElement.CHECKED_DATA_ELEMENT.TYPE;
    }

    @Override
    public Field<Timestamp> field5() {
        return CheckedDataElement.CHECKED_DATA_ELEMENT.CREATED_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getDataElementId();
    }

    @Override
    public CheckedDataElementType component4() {
        return getType();
    }

    @Override
    public Timestamp component5() {
        return getCreatedTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getDataElementId();
    }

    @Override
    public CheckedDataElementType value4() {
        return getType();
    }

    @Override
    public Timestamp value5() {
        return getCreatedTime();
    }

    @Override
    public CheckedDataElementRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CheckedDataElementRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CheckedDataElementRecord value3(Long value) {
        setDataElementId(value);
        return this;
    }

    @Override
    public CheckedDataElementRecord value4(CheckedDataElementType value) {
        setType(value);
        return this;
    }

    @Override
    public CheckedDataElementRecord value5(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public CheckedDataElementRecord values(Long value1, Long value2, Long value3, CheckedDataElementType value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public CheckedDataElementRecord() {
        super(CheckedDataElement.CHECKED_DATA_ELEMENT);
    }

    public CheckedDataElementRecord(Long id, Long userId, Long dataElementId, CheckedDataElementType type, Timestamp createdTime) {
        super(CheckedDataElement.CHECKED_DATA_ELEMENT);

        set(0, id);
        set(1, userId);
        set(2, dataElementId);
        set(3, type);
        set(4, createdTime);
    }
}
