/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 646151837;

    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    public final SpeechCollectionApp SPEECH_COLLECTION_APP = ch.fhnw.speech_collection_app.jooq.SpeechCollectionApp.SPEECH_COLLECTION_APP;

    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            SpeechCollectionApp.SPEECH_COLLECTION_APP);
    }
}
