/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq;


import ch.fhnw.speech_collection_app.jooq.tables.Achievements;
import ch.fhnw.speech_collection_app.jooq.tables.Audio;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataElement;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.DataElement;
import ch.fhnw.speech_collection_app.jooq.tables.DataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.Dialect;
import ch.fhnw.speech_collection_app.jooq.tables.FlywaySchemaHistory;
import ch.fhnw.speech_collection_app.jooq.tables.Image;
import ch.fhnw.speech_collection_app.jooq.tables.Source;
import ch.fhnw.speech_collection_app.jooq.tables.Text;
import ch.fhnw.speech_collection_app.jooq.tables.User;
import ch.fhnw.speech_collection_app.jooq.tables.UserAchievements;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroupRole;
import ch.fhnw.speech_collection_app.jooq.tables.VerificationToken;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACHIEVEMENTS_DOMAIN_ID = Indexes0.ACHIEVEMENTS_DOMAIN_ID;
    public static final Index AUDIO_DATA_ELEMENT_ID = Indexes0.AUDIO_DATA_ELEMENT_ID;
    public static final Index AUDIO_DIALECT_ID = Indexes0.AUDIO_DIALECT_ID;
    public static final Index CHECKED_DATA_ELEMENT_DATA_ELEMENT_ID = Indexes0.CHECKED_DATA_ELEMENT_DATA_ELEMENT_ID;
    public static final Index CHECKED_DATA_ELEMENT_USER_ID = Indexes0.CHECKED_DATA_ELEMENT_USER_ID;
    public static final Index CHECKED_DATA_TUPLE_DATA_TUPLE_ID = Indexes0.CHECKED_DATA_TUPLE_DATA_TUPLE_ID;
    public static final Index CHECKED_DATA_TUPLE_USER_ID = Indexes0.CHECKED_DATA_TUPLE_USER_ID;
    public static final Index DATA_ELEMENT_SOURCE_ID = Indexes0.DATA_ELEMENT_SOURCE_ID;
    public static final Index DATA_ELEMENT_USER_GROUP_ID = Indexes0.DATA_ELEMENT_USER_GROUP_ID;
    public static final Index DATA_ELEMENT_USER_ID = Indexes0.DATA_ELEMENT_USER_ID;
    public static final Index DATA_TUPLE_DATA_ELEMENT_ID_1 = Indexes0.DATA_TUPLE_DATA_ELEMENT_ID_1;
    public static final Index DATA_TUPLE_DATA_ELEMENT_ID_2 = Indexes0.DATA_TUPLE_DATA_ELEMENT_ID_2;
    public static final Index DIALECT_LANGUAGE_ID = Indexes0.DIALECT_LANGUAGE_ID;
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index IMAGE_DATA_ELEMENT_ID = Indexes0.IMAGE_DATA_ELEMENT_ID;
    public static final Index SOURCE_DIALECT_ID = Indexes0.SOURCE_DIALECT_ID;
    public static final Index SOURCE_DOMAIN_ID = Indexes0.SOURCE_DOMAIN_ID;
    public static final Index SOURCE_USER_GROUP_ID = Indexes0.SOURCE_USER_GROUP_ID;
    public static final Index SOURCE_USER_ID = Indexes0.SOURCE_USER_ID;
    public static final Index TEXT_DATA_ELEMENT_ID = Indexes0.TEXT_DATA_ELEMENT_ID;
    public static final Index TEXT_DIALECT_ID = Indexes0.TEXT_DIALECT_ID;
    public static final Index USER_DIALECT_ID = Indexes0.USER_DIALECT_ID;
    public static final Index USER_ACHIEVEMENTS_ACHIEVEMENTS_ID = Indexes0.USER_ACHIEVEMENTS_ACHIEVEMENTS_ID;
    public static final Index USER_ACHIEVEMENTS_USER_ID = Indexes0.USER_ACHIEVEMENTS_USER_ID;
    public static final Index USER_GROUP_ROLE_USER_GROUP_ID = Indexes0.USER_GROUP_ROLE_USER_GROUP_ID;
    public static final Index USER_GROUP_ROLE_USER_ID = Indexes0.USER_GROUP_ROLE_USER_ID;
    public static final Index VERIFICATION_TOKEN_USER_ID = Indexes0.VERIFICATION_TOKEN_USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACHIEVEMENTS_DOMAIN_ID = Internal.createIndex("domain_id", Achievements.ACHIEVEMENTS, new OrderField[] { Achievements.ACHIEVEMENTS.DOMAIN_ID }, false);
        public static Index AUDIO_DATA_ELEMENT_ID = Internal.createIndex("data_element_id", Audio.AUDIO, new OrderField[] { Audio.AUDIO.DATA_ELEMENT_ID }, false);
        public static Index AUDIO_DIALECT_ID = Internal.createIndex("dialect_id", Audio.AUDIO, new OrderField[] { Audio.AUDIO.DIALECT_ID }, false);
        public static Index CHECKED_DATA_ELEMENT_DATA_ELEMENT_ID = Internal.createIndex("data_element_id", CheckedDataElement.CHECKED_DATA_ELEMENT, new OrderField[] { CheckedDataElement.CHECKED_DATA_ELEMENT.DATA_ELEMENT_ID }, false);
        public static Index CHECKED_DATA_ELEMENT_USER_ID = Internal.createIndex("user_id", CheckedDataElement.CHECKED_DATA_ELEMENT, new OrderField[] { CheckedDataElement.CHECKED_DATA_ELEMENT.USER_ID }, false);
        public static Index CHECKED_DATA_TUPLE_DATA_TUPLE_ID = Internal.createIndex("data_tuple_id", CheckedDataTuple.CHECKED_DATA_TUPLE, new OrderField[] { CheckedDataTuple.CHECKED_DATA_TUPLE.DATA_TUPLE_ID }, false);
        public static Index CHECKED_DATA_TUPLE_USER_ID = Internal.createIndex("user_id", CheckedDataTuple.CHECKED_DATA_TUPLE, new OrderField[] { CheckedDataTuple.CHECKED_DATA_TUPLE.USER_ID }, false);
        public static Index DATA_ELEMENT_SOURCE_ID = Internal.createIndex("source_id", DataElement.DATA_ELEMENT, new OrderField[] { DataElement.DATA_ELEMENT.SOURCE_ID }, false);
        public static Index DATA_ELEMENT_USER_GROUP_ID = Internal.createIndex("user_group_id", DataElement.DATA_ELEMENT, new OrderField[] { DataElement.DATA_ELEMENT.USER_GROUP_ID }, false);
        public static Index DATA_ELEMENT_USER_ID = Internal.createIndex("user_id", DataElement.DATA_ELEMENT, new OrderField[] { DataElement.DATA_ELEMENT.USER_ID }, false);
        public static Index DATA_TUPLE_DATA_ELEMENT_ID_1 = Internal.createIndex("data_element_id_1", DataTuple.DATA_TUPLE, new OrderField[] { DataTuple.DATA_TUPLE.DATA_ELEMENT_ID_1 }, false);
        public static Index DATA_TUPLE_DATA_ELEMENT_ID_2 = Internal.createIndex("data_element_id_2", DataTuple.DATA_TUPLE, new OrderField[] { DataTuple.DATA_TUPLE.DATA_ELEMENT_ID_2 }, false);
        public static Index DIALECT_LANGUAGE_ID = Internal.createIndex("language_id", Dialect.DIALECT, new OrderField[] { Dialect.DIALECT.LANGUAGE_ID }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index IMAGE_DATA_ELEMENT_ID = Internal.createIndex("data_element_id", Image.IMAGE, new OrderField[] { Image.IMAGE.DATA_ELEMENT_ID }, false);
        public static Index SOURCE_DIALECT_ID = Internal.createIndex("dialect_id", Source.SOURCE, new OrderField[] { Source.SOURCE.DIALECT_ID }, false);
        public static Index SOURCE_DOMAIN_ID = Internal.createIndex("domain_id", Source.SOURCE, new OrderField[] { Source.SOURCE.DOMAIN_ID }, false);
        public static Index SOURCE_USER_GROUP_ID = Internal.createIndex("user_group_id", Source.SOURCE, new OrderField[] { Source.SOURCE.USER_GROUP_ID }, false);
        public static Index SOURCE_USER_ID = Internal.createIndex("user_id", Source.SOURCE, new OrderField[] { Source.SOURCE.USER_ID }, false);
        public static Index TEXT_DATA_ELEMENT_ID = Internal.createIndex("data_element_id", Text.TEXT, new OrderField[] { Text.TEXT.DATA_ELEMENT_ID }, false);
        public static Index TEXT_DIALECT_ID = Internal.createIndex("dialect_id", Text.TEXT, new OrderField[] { Text.TEXT.DIALECT_ID }, false);
        public static Index USER_DIALECT_ID = Internal.createIndex("dialect_id", User.USER, new OrderField[] { User.USER.DIALECT_ID }, false);
        public static Index USER_ACHIEVEMENTS_ACHIEVEMENTS_ID = Internal.createIndex("achievements_id", UserAchievements.USER_ACHIEVEMENTS, new OrderField[] { UserAchievements.USER_ACHIEVEMENTS.ACHIEVEMENTS_ID }, false);
        public static Index USER_ACHIEVEMENTS_USER_ID = Internal.createIndex("user_id", UserAchievements.USER_ACHIEVEMENTS, new OrderField[] { UserAchievements.USER_ACHIEVEMENTS.USER_ID }, false);
        public static Index USER_GROUP_ROLE_USER_GROUP_ID = Internal.createIndex("user_group_id", UserGroupRole.USER_GROUP_ROLE, new OrderField[] { UserGroupRole.USER_GROUP_ROLE.USER_GROUP_ID }, false);
        public static Index USER_GROUP_ROLE_USER_ID = Internal.createIndex("user_id", UserGroupRole.USER_GROUP_ROLE, new OrderField[] { UserGroupRole.USER_GROUP_ROLE.USER_ID }, false);
        public static Index VERIFICATION_TOKEN_USER_ID = Internal.createIndex("user_id", VerificationToken.VERIFICATION_TOKEN, new OrderField[] { VerificationToken.VERIFICATION_TOKEN.USER_ID }, false);
    }
}
