/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq;


import ch.fhnw.speech_collection_app.jooq.tables.Audio;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataElement;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.DataElement;
import ch.fhnw.speech_collection_app.jooq.tables.DataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.Dialect;
import ch.fhnw.speech_collection_app.jooq.tables.Domain;
import ch.fhnw.speech_collection_app.jooq.tables.FlywaySchemaHistory;
import ch.fhnw.speech_collection_app.jooq.tables.Image;
import ch.fhnw.speech_collection_app.jooq.tables.Language;
import ch.fhnw.speech_collection_app.jooq.tables.Source;
import ch.fhnw.speech_collection_app.jooq.tables.Text;
import ch.fhnw.speech_collection_app.jooq.tables.User;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroup;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroupRole;
import ch.fhnw.speech_collection_app.jooq.tables.VerificationToken;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeechCollectionApp extends SchemaImpl {

    private static final long serialVersionUID = 242600870;

    public static final SpeechCollectionApp SPEECH_COLLECTION_APP = new SpeechCollectionApp();

    public final Audio AUDIO = Audio.AUDIO;

    public final CheckedDataElement CHECKED_DATA_ELEMENT = CheckedDataElement.CHECKED_DATA_ELEMENT;

    public final CheckedDataTuple CHECKED_DATA_TUPLE = CheckedDataTuple.CHECKED_DATA_TUPLE;

    public final DataElement DATA_ELEMENT = DataElement.DATA_ELEMENT;

    public final DataTuple DATA_TUPLE = DataTuple.DATA_TUPLE;

    public final Dialect DIALECT = Dialect.DIALECT;

    public final Domain DOMAIN = Domain.DOMAIN;

    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    public final Image IMAGE = Image.IMAGE;

    public final Language LANGUAGE = Language.LANGUAGE;

    public final Source SOURCE = Source.SOURCE;

    public final Text TEXT = Text.TEXT;

    public final User USER = User.USER;

    public final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    public final UserGroupRole USER_GROUP_ROLE = UserGroupRole.USER_GROUP_ROLE;

    public final VerificationToken VERIFICATION_TOKEN = VerificationToken.VERIFICATION_TOKEN;

    private SpeechCollectionApp() {
        super("speech_collection_app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Audio.AUDIO,
            CheckedDataElement.CHECKED_DATA_ELEMENT,
            CheckedDataTuple.CHECKED_DATA_TUPLE,
            DataElement.DATA_ELEMENT,
            DataTuple.DATA_TUPLE,
            Dialect.DIALECT,
            Domain.DOMAIN,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Image.IMAGE,
            Language.LANGUAGE,
            Source.SOURCE,
            Text.TEXT,
            User.USER,
            UserGroup.USER_GROUP,
            UserGroupRole.USER_GROUP_ROLE,
            VerificationToken.VERIFICATION_TOKEN);
    }
}
