/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq;


import ch.fhnw.speech_collection_app.jooq.tables.CheckedRecording;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedTextAudio;
import ch.fhnw.speech_collection_app.jooq.tables.Dialect;
import ch.fhnw.speech_collection_app.jooq.tables.Domain;
import ch.fhnw.speech_collection_app.jooq.tables.Excerpt;
import ch.fhnw.speech_collection_app.jooq.tables.FlywaySchemaHistory;
import ch.fhnw.speech_collection_app.jooq.tables.Language;
import ch.fhnw.speech_collection_app.jooq.tables.OriginalText;
import ch.fhnw.speech_collection_app.jooq.tables.Recording;
import ch.fhnw.speech_collection_app.jooq.tables.Source;
import ch.fhnw.speech_collection_app.jooq.tables.Speaker;
import ch.fhnw.speech_collection_app.jooq.tables.TextAudio;
import ch.fhnw.speech_collection_app.jooq.tables.User;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroup;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroupRole;
import ch.fhnw.speech_collection_app.jooq.tables.VerificationToken;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeechCollectionApp extends SchemaImpl {

    private static final long serialVersionUID = -691132788;

    public static final SpeechCollectionApp SPEECH_COLLECTION_APP = new SpeechCollectionApp();

    public final CheckedRecording CHECKED_RECORDING = ch.fhnw.speech_collection_app.jooq.tables.CheckedRecording.CHECKED_RECORDING;

    public final CheckedTextAudio CHECKED_TEXT_AUDIO = ch.fhnw.speech_collection_app.jooq.tables.CheckedTextAudio.CHECKED_TEXT_AUDIO;

    public final Dialect DIALECT = ch.fhnw.speech_collection_app.jooq.tables.Dialect.DIALECT;

    public final Domain DOMAIN = ch.fhnw.speech_collection_app.jooq.tables.Domain.DOMAIN;

    public final Excerpt EXCERPT = ch.fhnw.speech_collection_app.jooq.tables.Excerpt.EXCERPT;

    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = ch.fhnw.speech_collection_app.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    public final Language LANGUAGE = ch.fhnw.speech_collection_app.jooq.tables.Language.LANGUAGE;

    public final OriginalText ORIGINAL_TEXT = ch.fhnw.speech_collection_app.jooq.tables.OriginalText.ORIGINAL_TEXT;

    public final Recording RECORDING = ch.fhnw.speech_collection_app.jooq.tables.Recording.RECORDING;

    public final Source SOURCE = ch.fhnw.speech_collection_app.jooq.tables.Source.SOURCE;

    public final Speaker SPEAKER = ch.fhnw.speech_collection_app.jooq.tables.Speaker.SPEAKER;

    public final TextAudio TEXT_AUDIO = ch.fhnw.speech_collection_app.jooq.tables.TextAudio.TEXT_AUDIO;

    public final User USER = ch.fhnw.speech_collection_app.jooq.tables.User.USER;

    public final UserGroup USER_GROUP = ch.fhnw.speech_collection_app.jooq.tables.UserGroup.USER_GROUP;

    public final UserGroupRole USER_GROUP_ROLE = ch.fhnw.speech_collection_app.jooq.tables.UserGroupRole.USER_GROUP_ROLE;

    public final VerificationToken VERIFICATION_TOKEN = ch.fhnw.speech_collection_app.jooq.tables.VerificationToken.VERIFICATION_TOKEN;

    private SpeechCollectionApp() {
        super("speech_collection_app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CheckedRecording.CHECKED_RECORDING,
            CheckedTextAudio.CHECKED_TEXT_AUDIO,
            Dialect.DIALECT,
            Domain.DOMAIN,
            Excerpt.EXCERPT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Language.LANGUAGE,
            OriginalText.ORIGINAL_TEXT,
            Recording.RECORDING,
            Source.SOURCE,
            Speaker.SPEAKER,
            TextAudio.TEXT_AUDIO,
            User.USER,
            UserGroup.USER_GROUP,
            UserGroupRole.USER_GROUP_ROLE,
            VerificationToken.VERIFICATION_TOKEN);
    }
}
