/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq;


import ch.fhnw.speech_collection_app.jooq.tables.Audio;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataElement;
import ch.fhnw.speech_collection_app.jooq.tables.CheckedDataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.DataElement;
import ch.fhnw.speech_collection_app.jooq.tables.DataTuple;
import ch.fhnw.speech_collection_app.jooq.tables.Dialect;
import ch.fhnw.speech_collection_app.jooq.tables.Domain;
import ch.fhnw.speech_collection_app.jooq.tables.FlywaySchemaHistory;
import ch.fhnw.speech_collection_app.jooq.tables.Image;
import ch.fhnw.speech_collection_app.jooq.tables.Language;
import ch.fhnw.speech_collection_app.jooq.tables.Source;
import ch.fhnw.speech_collection_app.jooq.tables.Text;
import ch.fhnw.speech_collection_app.jooq.tables.User;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroup;
import ch.fhnw.speech_collection_app.jooq.tables.UserGroupRole;
import ch.fhnw.speech_collection_app.jooq.tables.VerificationToken;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    public static final Audio AUDIO = Audio.AUDIO;

    public static final CheckedDataElement CHECKED_DATA_ELEMENT = CheckedDataElement.CHECKED_DATA_ELEMENT;

    public static final CheckedDataTuple CHECKED_DATA_TUPLE = CheckedDataTuple.CHECKED_DATA_TUPLE;

    public static final DataElement DATA_ELEMENT = DataElement.DATA_ELEMENT;

    public static final DataTuple DATA_TUPLE = DataTuple.DATA_TUPLE;

    public static final Dialect DIALECT = Dialect.DIALECT;

    public static final Domain DOMAIN = Domain.DOMAIN;

    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    public static final Image IMAGE = Image.IMAGE;

    public static final Language LANGUAGE = Language.LANGUAGE;

    public static final Source SOURCE = Source.SOURCE;

    public static final Text TEXT = Text.TEXT;

    public static final User USER = User.USER;

    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    public static final UserGroupRole USER_GROUP_ROLE = UserGroupRole.USER_GROUP_ROLE;

    public static final VerificationToken VERIFICATION_TOKEN = VerificationToken.VERIFICATION_TOKEN;
}
