/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables.daos;


import ch.fhnw.speech_collection_app.jooq.tables.Source;
import ch.fhnw.speech_collection_app.jooq.tables.records.SourceRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SourceDao extends DAOImpl<SourceRecord, ch.fhnw.speech_collection_app.jooq.tables.pojos.Source, Long> {

    public SourceDao() {
        super(Source.SOURCE, ch.fhnw.speech_collection_app.jooq.tables.pojos.Source.class);
    }

    @Autowired
    public SourceDao(Configuration configuration) {
        super(Source.SOURCE, ch.fhnw.speech_collection_app.jooq.tables.pojos.Source.class, configuration);
    }

    @Override
    public Long getId(ch.fhnw.speech_collection_app.jooq.tables.pojos.Source object) {
        return object.getId();
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Source.SOURCE.ID, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchById(Long... values) {
        return fetch(Source.SOURCE.ID, values);
    }

    public ch.fhnw.speech_collection_app.jooq.tables.pojos.Source fetchOneById(Long value) {
        return fetchOne(Source.SOURCE.ID, value);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Source.SOURCE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchByDescription(String... values) {
        return fetch(Source.SOURCE.DESCRIPTION, values);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Source.SOURCE.NAME, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchByName(String... values) {
        return fetch(Source.SOURCE.NAME, values);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfRawAudioPath(String lowerInclusive, String upperInclusive) {
        return fetchRange(Source.SOURCE.RAW_AUDIO_PATH, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchByRawAudioPath(String... values) {
        return fetch(Source.SOURCE.RAW_AUDIO_PATH, values);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfRawFilePath(String lowerInclusive, String upperInclusive) {
        return fetchRange(Source.SOURCE.RAW_FILE_PATH, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchByRawFilePath(String... values) {
        return fetch(Source.SOURCE.RAW_FILE_PATH, values);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchRangeOfLicence(String lowerInclusive, String upperInclusive) {
        return fetchRange(Source.SOURCE.LICENCE, lowerInclusive, upperInclusive);
    }

    public List<ch.fhnw.speech_collection_app.jooq.tables.pojos.Source> fetchByLicence(String... values) {
        return fetch(Source.SOURCE.LICENCE, values);
    }
}
