spring:
  datasource:
    password: labeling-tool
    username: labeling-tool
    url: jdbc:mysql://localhost/labeling-tool
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8084
labeling-tool:
  base-path: /home/stt/labeling-tool/data
  conda-exec: "/home/stt/miniconda3/condabin/conda run -n labeling_tool python /home/stt/labeling-tool/data_import/sentences.py"
