spring:
  datasource:
    password: speech_collection_app
    username: speech_collection_app
    url: jdbc:mysql://localhost/speech_collection_app
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    banner-mode: off
server:
  port: 8084
speech-collection-app:
  base-path: /home/vzuest/Dokumente/speech-collection-app/data/
  conda-exec: "/home/vzuest/Dokumente/miniconda3/condabin/conda run -n speech_collection_app python /home/vzuest/Dokumente/speech-collection-app/data_import/sentences.py"
  public-group-id: 1
  features:
    email-integration: false
  min-num-checks: 3
