spring:
  datasource:
    password: speech_collection_app
    username: speech_collection_app
    url: jdbc:mysql://localhost/speech_collection_app
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    banner-mode: off
server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
speech-collection-app:
  base-path: /home/stt/speech-collection-app/data/
  conda-exec: "/home/stt/miniconda3/condabin/conda run -n speech_collection_app python /home/stt/speech-collection-app/data_import/sentences.py"
  public-group-id: 1
  features:
    email-integration: false
    additional-data: true
    swiss-german-text: false
    images: false
    gamification:
      mode: enabled
      point-per-level: [0,10,20,50,100]
      daily-divisor: 2
  min-num-checks: 3
  num-random-select: 40
