/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.tables;


import ch.fhnw.speech_collection_app.jooq.Indexes;
import ch.fhnw.speech_collection_app.jooq.Keys;
import ch.fhnw.speech_collection_app.jooq.SpeechCollectionApp;
import ch.fhnw.speech_collection_app.jooq.enums.CheckedDataElementType;
import ch.fhnw.speech_collection_app.jooq.tables.records.CheckedDataElementRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckedDataElement extends TableImpl<CheckedDataElementRecord> {

    private static final long serialVersionUID = -756371125;

    public static final CheckedDataElement CHECKED_DATA_ELEMENT = new CheckedDataElement();

    @Override
    public Class<CheckedDataElementRecord> getRecordType() {
        return CheckedDataElementRecord.class;
    }

    public final TableField<CheckedDataElementRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    public final TableField<CheckedDataElementRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<CheckedDataElementRecord, Long> DATA_ELEMENT_ID = createField(DSL.name("data_element_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<CheckedDataElementRecord, CheckedDataElementType> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(14).nullable(false).asEnumDataType(ch.fhnw.speech_collection_app.jooq.enums.CheckedDataElementType.class), this, "");

    public final TableField<CheckedDataElementRecord, Timestamp> CREATED_TIME = createField(DSL.name("created_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    public CheckedDataElement() {
        this(DSL.name("checked_data_element"), null);
    }

    public CheckedDataElement(String alias) {
        this(DSL.name(alias), CHECKED_DATA_ELEMENT);
    }

    public CheckedDataElement(Name alias) {
        this(alias, CHECKED_DATA_ELEMENT);
    }

    private CheckedDataElement(Name alias, Table<CheckedDataElementRecord> aliased) {
        this(alias, aliased, null);
    }

    private CheckedDataElement(Name alias, Table<CheckedDataElementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("this table is used to save the label of a data_element by a user so we can revert it in case a user produces nonsense"));
    }

    public <O extends Record> CheckedDataElement(Table<O> child, ForeignKey<O, CheckedDataElementRecord> key) {
        super(child, key, CHECKED_DATA_ELEMENT);
    }

    @Override
    public Schema getSchema() {
        return SpeechCollectionApp.SPEECH_COLLECTION_APP;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHECKED_DATA_ELEMENT_DATA_ELEMENT_ID, Indexes.CHECKED_DATA_ELEMENT_PRIMARY, Indexes.CHECKED_DATA_ELEMENT_USER_ID);
    }

    @Override
    public Identity<CheckedDataElementRecord, Long> getIdentity() {
        return Keys.IDENTITY_CHECKED_DATA_ELEMENT;
    }

    @Override
    public UniqueKey<CheckedDataElementRecord> getPrimaryKey() {
        return Keys.KEY_CHECKED_DATA_ELEMENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<CheckedDataElementRecord>> getKeys() {
        return Arrays.<UniqueKey<CheckedDataElementRecord>>asList(Keys.KEY_CHECKED_DATA_ELEMENT_PRIMARY);
    }

    @Override
    public List<ForeignKey<CheckedDataElementRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CheckedDataElementRecord, ?>>asList(Keys.CHECKED_DATA_ELEMENT_IBFK_1, Keys.CHECKED_DATA_ELEMENT_IBFK_2);
    }

    public User user() {
        return new User(this, Keys.CHECKED_DATA_ELEMENT_IBFK_1);
    }

    public DataElement dataElement() {
        return new DataElement(this, Keys.CHECKED_DATA_ELEMENT_IBFK_2);
    }

    @Override
    public CheckedDataElement as(String alias) {
        return new CheckedDataElement(DSL.name(alias), this);
    }

    @Override
    public CheckedDataElement as(Name alias) {
        return new CheckedDataElement(alias, this);
    }

    @Override
    public CheckedDataElement rename(String name) {
        return new CheckedDataElement(DSL.name(name), null);
    }

    @Override
    public CheckedDataElement rename(Name name) {
        return new CheckedDataElement(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, CheckedDataElementType, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
