/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AudioNoiseLevel implements EnumType {

    NO_NOISE("NO_NOISE"),

    MODERATE_NOISE("MODERATE_NOISE"),

    VERY_NOISY("VERY_NOISY");

    private final String literal;

    private AudioNoiseLevel(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "audio_noise_level";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
