/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DataTupleType implements EnumType {

    TEXT_TEXT("TEXT_TEXT"),

    AUDIO_AUDIO("AUDIO_AUDIO"),

    TEXT_AUDIO("TEXT_AUDIO"),

    AUDIO_TEXT("AUDIO_TEXT"),

    IMAGE_AUDIO("IMAGE_AUDIO"),

    RECORDING("RECORDING");

    private final String literal;

    private DataTupleType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "data_tuple_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
