/*
 * This file is generated by jOOQ.
 */
package ch.fhnw.speech_collection_app.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum VerificationTokenTokenType implements EnumType {

    EMAIL("EMAIL"),

    PASSWORD("PASSWORD");

    private final String literal;

    private VerificationTokenTokenType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "verification_token_token_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
